/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2023-09-06
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.MerchantBrandListResult;
import com.alipay.v3.model.MiniappBrandAuditResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayOpenMiniMiniappBrandQueryResponseModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayOpenMiniMiniappBrandQueryResponseModel {
  public static final String SERIALIZED_NAME_MERCHANT_BRAND_LIST_RESULT = "merchant_brand_list_result";
  @SerializedName(SERIALIZED_NAME_MERCHANT_BRAND_LIST_RESULT)
  private MerchantBrandListResult merchantBrandListResult;

  public static final String SERIALIZED_NAME_MINIAPP_BRAND_AUDIT_RESULT = "miniapp_brand_audit_result";
  @SerializedName(SERIALIZED_NAME_MINIAPP_BRAND_AUDIT_RESULT)
  private MiniappBrandAuditResult miniappBrandAuditResult;

  public AlipayOpenMiniMiniappBrandQueryResponseModel() { 
  }

  public AlipayOpenMiniMiniappBrandQueryResponseModel merchantBrandListResult(MerchantBrandListResult merchantBrandListResult) {
    
    this.merchantBrandListResult = merchantBrandListResult;
    return this;
  }

   /**
   * Get merchantBrandListResult
   * @return merchantBrandListResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MerchantBrandListResult getMerchantBrandListResult() {
    return merchantBrandListResult;
  }


  public void setMerchantBrandListResult(MerchantBrandListResult merchantBrandListResult) {
    this.merchantBrandListResult = merchantBrandListResult;
  }


  public AlipayOpenMiniMiniappBrandQueryResponseModel miniappBrandAuditResult(MiniappBrandAuditResult miniappBrandAuditResult) {
    
    this.miniappBrandAuditResult = miniappBrandAuditResult;
    return this;
  }

   /**
   * Get miniappBrandAuditResult
   * @return miniappBrandAuditResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MiniappBrandAuditResult getMiniappBrandAuditResult() {
    return miniappBrandAuditResult;
  }


  public void setMiniappBrandAuditResult(MiniappBrandAuditResult miniappBrandAuditResult) {
    this.miniappBrandAuditResult = miniappBrandAuditResult;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayOpenMiniMiniappBrandQueryResponseModel alipayOpenMiniMiniappBrandQueryResponseModel = (AlipayOpenMiniMiniappBrandQueryResponseModel) o;
    return Objects.equals(this.merchantBrandListResult, alipayOpenMiniMiniappBrandQueryResponseModel.merchantBrandListResult) &&
        Objects.equals(this.miniappBrandAuditResult, alipayOpenMiniMiniappBrandQueryResponseModel.miniappBrandAuditResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantBrandListResult, miniappBrandAuditResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayOpenMiniMiniappBrandQueryResponseModel {\n");
    sb.append("    merchantBrandListResult: ").append(toIndentedString(merchantBrandListResult)).append("\n");
    sb.append("    miniappBrandAuditResult: ").append(toIndentedString(miniappBrandAuditResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("merchant_brand_list_result");
    openapiFields.add("miniapp_brand_audit_result");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayOpenMiniMiniappBrandQueryResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayOpenMiniMiniappBrandQueryResponseModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayOpenMiniMiniappBrandQueryResponseModel is not found in the empty JSON string", AlipayOpenMiniMiniappBrandQueryResponseModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AlipayOpenMiniMiniappBrandQueryResponseModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AlipayOpenMiniMiniappBrandQueryResponseModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `merchant_brand_list_result`
      if (jsonObj.getAsJsonObject("merchant_brand_list_result") != null) {
        MerchantBrandListResult.validateJsonObject(jsonObj.getAsJsonObject("merchant_brand_list_result"));
      }
      // validate the optional field `miniapp_brand_audit_result`
      if (jsonObj.getAsJsonObject("miniapp_brand_audit_result") != null) {
        MiniappBrandAuditResult.validateJsonObject(jsonObj.getAsJsonObject("miniapp_brand_audit_result"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayOpenMiniMiniappBrandQueryResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayOpenMiniMiniappBrandQueryResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayOpenMiniMiniappBrandQueryResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayOpenMiniMiniappBrandQueryResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayOpenMiniMiniappBrandQueryResponseModel>() {
           @Override
           public void write(JsonWriter out, AlipayOpenMiniMiniappBrandQueryResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayOpenMiniMiniappBrandQueryResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayOpenMiniMiniappBrandQueryResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayOpenMiniMiniappBrandQueryResponseModel
  * @throws IOException if the JSON string is invalid with respect to AlipayOpenMiniMiniappBrandQueryResponseModel
  */
  public static AlipayOpenMiniMiniappBrandQueryResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayOpenMiniMiniappBrandQueryResponseModel.class);
  }

 /**
  * Convert an instance of AlipayOpenMiniMiniappBrandQueryResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

