/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2023-04-27
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.Marketingtest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayMarketingXuanyitestTransferResponseModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayMarketingXuanyitestTransferResponseModel {
  public static final String SERIALIZED_NAME_TEST = "test";
  @SerializedName(SERIALIZED_NAME_TEST)
  private List<String> test = null;

  public static final String SERIALIZED_NAME_TEST21 = "test_21";
  @SerializedName(SERIALIZED_NAME_TEST21)
  private List<Marketingtest> test21 = null;

  public AlipayMarketingXuanyitestTransferResponseModel() { 
  }

  public AlipayMarketingXuanyitestTransferResponseModel test(List<String> test) {
    
    this.test = test;
    return this;
  }

  public AlipayMarketingXuanyitestTransferResponseModel addTestItem(String testItem) {
    if (this.test == null) {
      this.test = new ArrayList<>();
    }
    this.test.add(testItem);
    return this;
  }

   /**
   * 12
   * @return test
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"11\",\"12\"]", value = "12")

  public List<String> getTest() {
    return test;
  }


  public void setTest(List<String> test) {
    this.test = test;
  }


  public AlipayMarketingXuanyitestTransferResponseModel test21(List<Marketingtest> test21) {
    
    this.test21 = test21;
    return this;
  }

  public AlipayMarketingXuanyitestTransferResponseModel addTest21Item(Marketingtest test21Item) {
    if (this.test21 == null) {
      this.test21 = new ArrayList<>();
    }
    this.test21.add(test21Item);
    return this;
  }

   /**
   * 测试复杂类型描述
   * @return test21
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "测试复杂类型描述")

  public List<Marketingtest> getTest21() {
    return test21;
  }


  public void setTest21(List<Marketingtest> test21) {
    this.test21 = test21;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayMarketingXuanyitestTransferResponseModel alipayMarketingXuanyitestTransferResponseModel = (AlipayMarketingXuanyitestTransferResponseModel) o;
    return Objects.equals(this.test, alipayMarketingXuanyitestTransferResponseModel.test) &&
        Objects.equals(this.test21, alipayMarketingXuanyitestTransferResponseModel.test21);
  }

  @Override
  public int hashCode() {
    return Objects.hash(test, test21);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayMarketingXuanyitestTransferResponseModel {\n");
    sb.append("    test: ").append(toIndentedString(test)).append("\n");
    sb.append("    test21: ").append(toIndentedString(test21)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("test");
    openapiFields.add("test_21");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayMarketingXuanyitestTransferResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayMarketingXuanyitestTransferResponseModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayMarketingXuanyitestTransferResponseModel is not found in the empty JSON string", AlipayMarketingXuanyitestTransferResponseModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AlipayMarketingXuanyitestTransferResponseModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AlipayMarketingXuanyitestTransferResponseModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("test") != null && !jsonObj.get("test").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `test` to be an array in the JSON string but got `%s`", jsonObj.get("test").toString()));
      }
      JsonArray jsonArraytest21 = jsonObj.getAsJsonArray("test_21");
      if (jsonArraytest21 != null) {
        // ensure the json data is an array
        if (!jsonObj.get("test_21").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `test_21` to be an array in the JSON string but got `%s`", jsonObj.get("test_21").toString()));
        }

        // validate the optional field `test_21` (array)
        for (int i = 0; i < jsonArraytest21.size(); i++) {
          Marketingtest.validateJsonObject(jsonArraytest21.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayMarketingXuanyitestTransferResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayMarketingXuanyitestTransferResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayMarketingXuanyitestTransferResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayMarketingXuanyitestTransferResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayMarketingXuanyitestTransferResponseModel>() {
           @Override
           public void write(JsonWriter out, AlipayMarketingXuanyitestTransferResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayMarketingXuanyitestTransferResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayMarketingXuanyitestTransferResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayMarketingXuanyitestTransferResponseModel
  * @throws IOException if the JSON string is invalid with respect to AlipayMarketingXuanyitestTransferResponseModel
  */
  public static AlipayMarketingXuanyitestTransferResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayMarketingXuanyitestTransferResponseModel.class);
  }

 /**
  * Convert an instance of AlipayMarketingXuanyitestTransferResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

