/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2024-01-10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayUserUserinfoShareModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayUserUserinfoShareModel {
  public static final String SERIALIZED_NAME_WE = "we";
  @SerializedName(SERIALIZED_NAME_WE)
  private String we;

  public AlipayUserUserinfoShareModel() { 
  }

  public AlipayUserUserinfoShareModel we(String we) {
    
    this.we = we;
    return this;
  }

   /**
   * daf
   * @return we
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "we", value = "daf")

  public String getWe() {
    return we;
  }


  public void setWe(String we) {
    this.we = we;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayUserUserinfoShareModel alipayUserUserinfoShareModel = (AlipayUserUserinfoShareModel) o;
    return Objects.equals(this.we, alipayUserUserinfoShareModel.we);
  }

  @Override
  public int hashCode() {
    return Objects.hash(we);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayUserUserinfoShareModel {\n");
    sb.append("    we: ").append(toIndentedString(we)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("we");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayUserUserinfoShareModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayUserUserinfoShareModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayUserUserinfoShareModel is not found in the empty JSON string", AlipayUserUserinfoShareModel.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AlipayUserUserinfoShareModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AlipayUserUserinfoShareModel` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("we") != null && !jsonObj.get("we").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `we` to be a primitive type in the JSON string but got `%s`", jsonObj.get("we").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayUserUserinfoShareModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayUserUserinfoShareModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayUserUserinfoShareModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayUserUserinfoShareModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayUserUserinfoShareModel>() {
           @Override
           public void write(JsonWriter out, AlipayUserUserinfoShareModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayUserUserinfoShareModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayUserUserinfoShareModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayUserUserinfoShareModel
  * @throws IOException if the JSON string is invalid with respect to AlipayUserUserinfoShareModel
  */
  public static AlipayUserUserinfoShareModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayUserUserinfoShareModel.class);
  }

 /**
  * Convert an instance of AlipayUserUserinfoShareModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

