/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2024-01-12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.ExpenseCtrlEmployeeRuleInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel {
  public static final String SERIALIZED_NAME_EMPLOYEE_RULES = "employee_rules";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_RULES)
  private List<ExpenseCtrlEmployeeRuleInfo> employeeRules = null;

  public static final String SERIALIZED_NAME_PAGE_NUM = "page_num";
  @SerializedName(SERIALIZED_NAME_PAGE_NUM)
  private Integer pageNum;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  private Integer pageSize;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Integer totalCount;

  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel() { 
  }

  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel employeeRules(List<ExpenseCtrlEmployeeRuleInfo> employeeRules) {
    
    this.employeeRules = employeeRules;
    return this;
  }

  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel addEmployeeRulesItem(ExpenseCtrlEmployeeRuleInfo employeeRulesItem) {
    if (this.employeeRules == null) {
      this.employeeRules = new ArrayList<>();
    }
    this.employeeRules.add(employeeRulesItem);
    return this;
  }

   /**
   * 员工已绑定费控规则列表
   * @return employeeRules
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "员工已绑定费控规则列表")

  public List<ExpenseCtrlEmployeeRuleInfo> getEmployeeRules() {
    return employeeRules;
  }


  public void setEmployeeRules(List<ExpenseCtrlEmployeeRuleInfo> employeeRules) {
    this.employeeRules = employeeRules;
  }


  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel pageNum(Integer pageNum) {
    
    this.pageNum = pageNum;
    return this;
  }

   /**
   * 客户端输入的页码
   * @return pageNum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "客户端输入的页码")

  public Integer getPageNum() {
    return pageNum;
  }


  public void setPageNum(Integer pageNum) {
    this.pageNum = pageNum;
  }


  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * 客户端输入的每页行数
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20", value = "客户端输入的每页行数")

  public Integer getPageSize() {
    return pageSize;
  }


  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel totalCount(Integer totalCount) {
    
    this.totalCount = totalCount;
    return this;
  }

   /**
   * 查询到的实例总数
   * @return totalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100", value = "查询到的实例总数")

  public Integer getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel instance itself
   */
  public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel = (AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel) o;
    return Objects.equals(this.employeeRules, alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.employeeRules) &&
        Objects.equals(this.pageNum, alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.pageNum) &&
        Objects.equals(this.pageSize, alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.pageSize) &&
        Objects.equals(this.totalCount, alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.totalCount)&&
        Objects.equals(this.additionalProperties, alipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeRules, pageNum, pageSize, totalCount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel {\n");
    sb.append("    employeeRules: ").append(toIndentedString(employeeRules)).append("\n");
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("employee_rules");
    openapiFields.add("page_num");
    openapiFields.add("page_size");
    openapiFields.add("total_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel is not found in the empty JSON string", AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.openapiRequiredFields.toString()));
        }
      }
      JsonArray jsonArrayemployeeRules = jsonObj.getAsJsonArray("employee_rules");
      if (jsonArrayemployeeRules != null) {
        // ensure the json data is an array
        if (!jsonObj.get("employee_rules").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `employee_rules` to be an array in the JSON string but got `%s`", jsonObj.get("employee_rules").toString()));
        }

        // validate the optional field `employee_rules` (array)
        for (int i = 0; i < jsonArrayemployeeRules.size(); i++) {
          ExpenseCtrlEmployeeRuleInfo.validateJsonObject(jsonArrayemployeeRules.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel>() {
           @Override
           public void write(JsonWriter out, AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else { // non-primitive type
                   instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel
  * @throws IOException if the JSON string is invalid with respect to AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel
  */
  public static AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel.class);
  }

 /**
  * Convert an instance of AlipayEbppInvoiceExpenserulesEmployeerulesQueryResponseModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

