/*
 * 支付宝开放平台API
 * 支付宝开放平台v3协议文档
 *
 * The version of the OpenAPI document: 2023-07-17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alipay.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.alipay.v3.model.DateRuleInfo;
import com.alipay.v3.model.HolidayRuleInfo;
import com.alipay.v3.model.WeekRuleInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.alipay.v3.JSON;

/**
 * VoucherUseTimeRuleInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class VoucherUseTimeRuleInfo {
  public static final String SERIALIZED_NAME_DATE_RULE_INFO = "date_rule_info";
  @SerializedName(SERIALIZED_NAME_DATE_RULE_INFO)
  private DateRuleInfo dateRuleInfo;

  public static final String SERIALIZED_NAME_HOLIDAY_RULE_INFO = "holiday_rule_info";
  @SerializedName(SERIALIZED_NAME_HOLIDAY_RULE_INFO)
  private HolidayRuleInfo holidayRuleInfo;

  public static final String SERIALIZED_NAME_RULE_TYPE = "rule_type";
  @SerializedName(SERIALIZED_NAME_RULE_TYPE)
  private String ruleType;

  public static final String SERIALIZED_NAME_WEEK_RULE_INFO = "week_rule_info";
  @SerializedName(SERIALIZED_NAME_WEEK_RULE_INFO)
  private WeekRuleInfo weekRuleInfo;

  public VoucherUseTimeRuleInfo() { 
  }

  public VoucherUseTimeRuleInfo dateRuleInfo(DateRuleInfo dateRuleInfo) {
    
    this.dateRuleInfo = dateRuleInfo;
    return this;
  }

   /**
   * Get dateRuleInfo
   * @return dateRuleInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateRuleInfo getDateRuleInfo() {
    return dateRuleInfo;
  }


  public void setDateRuleInfo(DateRuleInfo dateRuleInfo) {
    this.dateRuleInfo = dateRuleInfo;
  }


  public VoucherUseTimeRuleInfo holidayRuleInfo(HolidayRuleInfo holidayRuleInfo) {
    
    this.holidayRuleInfo = holidayRuleInfo;
    return this;
  }

   /**
   * Get holidayRuleInfo
   * @return holidayRuleInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HolidayRuleInfo getHolidayRuleInfo() {
    return holidayRuleInfo;
  }


  public void setHolidayRuleInfo(HolidayRuleInfo holidayRuleInfo) {
    this.holidayRuleInfo = holidayRuleInfo;
  }


  public VoucherUseTimeRuleInfo ruleType(String ruleType) {
    
    this.ruleType = ruleType;
    return this;
  }

   /**
   * 规则类型
   * @return ruleType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "规则类型")

  public String getRuleType() {
    return ruleType;
  }


  public void setRuleType(String ruleType) {
    this.ruleType = ruleType;
  }


  public VoucherUseTimeRuleInfo weekRuleInfo(WeekRuleInfo weekRuleInfo) {
    
    this.weekRuleInfo = weekRuleInfo;
    return this;
  }

   /**
   * Get weekRuleInfo
   * @return weekRuleInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WeekRuleInfo getWeekRuleInfo() {
    return weekRuleInfo;
  }


  public void setWeekRuleInfo(WeekRuleInfo weekRuleInfo) {
    this.weekRuleInfo = weekRuleInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoucherUseTimeRuleInfo voucherUseTimeRuleInfo = (VoucherUseTimeRuleInfo) o;
    return Objects.equals(this.dateRuleInfo, voucherUseTimeRuleInfo.dateRuleInfo) &&
        Objects.equals(this.holidayRuleInfo, voucherUseTimeRuleInfo.holidayRuleInfo) &&
        Objects.equals(this.ruleType, voucherUseTimeRuleInfo.ruleType) &&
        Objects.equals(this.weekRuleInfo, voucherUseTimeRuleInfo.weekRuleInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateRuleInfo, holidayRuleInfo, ruleType, weekRuleInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoucherUseTimeRuleInfo {\n");
    sb.append("    dateRuleInfo: ").append(toIndentedString(dateRuleInfo)).append("\n");
    sb.append("    holidayRuleInfo: ").append(toIndentedString(holidayRuleInfo)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("    weekRuleInfo: ").append(toIndentedString(weekRuleInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date_rule_info");
    openapiFields.add("holiday_rule_info");
    openapiFields.add("rule_type");
    openapiFields.add("week_rule_info");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VoucherUseTimeRuleInfo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (VoucherUseTimeRuleInfo.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in VoucherUseTimeRuleInfo is not found in the empty JSON string", VoucherUseTimeRuleInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!VoucherUseTimeRuleInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VoucherUseTimeRuleInfo` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `date_rule_info`
      if (jsonObj.getAsJsonObject("date_rule_info") != null) {
        DateRuleInfo.validateJsonObject(jsonObj.getAsJsonObject("date_rule_info"));
      }
      // validate the optional field `holiday_rule_info`
      if (jsonObj.getAsJsonObject("holiday_rule_info") != null) {
        HolidayRuleInfo.validateJsonObject(jsonObj.getAsJsonObject("holiday_rule_info"));
      }
      if (jsonObj.get("rule_type") != null && !jsonObj.get("rule_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rule_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rule_type").toString()));
      }
      // validate the optional field `week_rule_info`
      if (jsonObj.getAsJsonObject("week_rule_info") != null) {
        WeekRuleInfo.validateJsonObject(jsonObj.getAsJsonObject("week_rule_info"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VoucherUseTimeRuleInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VoucherUseTimeRuleInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VoucherUseTimeRuleInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VoucherUseTimeRuleInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<VoucherUseTimeRuleInfo>() {
           @Override
           public void write(JsonWriter out, VoucherUseTimeRuleInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VoucherUseTimeRuleInfo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VoucherUseTimeRuleInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VoucherUseTimeRuleInfo
  * @throws IOException if the JSON string is invalid with respect to VoucherUseTimeRuleInfo
  */
  public static VoucherUseTimeRuleInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VoucherUseTimeRuleInfo.class);
  }

 /**
  * Convert an instance of VoucherUseTimeRuleInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

